Public Class ArsClientContract
   Public Property ClientContractId As Integer
   Public Property ClientContractStatusId As Integer
   Public Property PlatformId As Integer
   Public Property OrgId As Integer
   Public Property ClusterId As Integer
   Public Property ContractTypeId As Integer
   Public Property ClientId As Integer
   Public Property ClientName As String
   Public Property ClientContractName As String
   Public Property ContactDetailId As Integer
    Public Property ContactPerson As String
    Public Property ContactPosition As String
    Public Property ContactNumber As String
    Public Property RegionId As String
   Public Property ProvinceId As String
   Public Property MunicipalityId As String
   Public Property ContractDate As Date
   Public Property NotarizeDate As Date
   Public Property ClientContractCRN As String
   Public Property AdminFee As Decimal
   Public Property StartDate As Date
   Public Property EndDate As Date
   Public Property PaymentTerms As Integer
   Public Property BankId As Integer
   Public Property PenaltyFlag As Boolean
   Public Property AdvancePaymentFlag As Boolean
   Public Property SeparationPayId As Integer
   Public Property SeparationPayBillingId As Integer
   Public Property RetirementPayId As Integer
   Public Property RetirementPayBillingId As Integer
   Public Property ThirteenMonthPayId As Integer
   Public Property ThirteenMonthPayBillingId As Integer
   Public Property ApeChargeId As Integer
   Public Property PpeChargeId As Integer
   Public Property UniformChargeId As Integer
   Public Property OshTrainingChargeId As Integer
   Public Property OshPersonnelChargeId As Integer
   Public Property OtherProvisions As String
   Public Property SpecialArrangement As String
   Public Property ForceMajeurFlag As Boolean
   Public Property NonCompeteFlag As Boolean
   Public Property PenaltyChargeFlag As Boolean
   Public Property PenaltyChargeDetails As String
   Public Property BondProvisionFlag As Boolean
   Public Property NdaFlag As Boolean
   Public Property Remarks As String
   Public Property LockId As String

End Class
